print("Hello I am your Friendly rigorous entertainment deivice or you can call me F.R.E.D")
name = input ("What is your name\n")
print("Hello " + name)
name1 = input ("What is your favorite subject in school\n")
print(name1 + ", well I like math" )
name2 = input ("What is your favorite color\n") 
print("That is cool my favorite color is purple ")
name3 = input ("What is your favorite movie\n")
print("Oh " + name3 + " The Sand Lot")
name4 = input ("What is your favorite sport\n")
print(name4 + " that is cool I like playing Baseball")
print("Thank you for chatting with F.R.E.D.")
print("F.R.E.D. Created by ##### G")
print("F.R.E.D. part 2 coming soon?")